! This file contains three subroutines that are used to allocate memory
! for variables that are defined in PARAMS.
!
! The vast majority of variables are allocated in the PARAMS_ALLOC subroutine.
! However, some variables must be allocated for SET_IO, which is called before PARAMS_ALLOC.
! Additionally, the DEM grid size is not known until midway through PREPROCESSING, so there
! is a third allocation subroutine for the DEM grid mapping array.
    
subroutine params_alloc_io
    ! separate subroutine to allocate memory for variables defined in PARAMS but read in subroutine: SET_IO
    use params
    implicit none
    
    allocate(FIBS_intvals(6))
    allocate(spsal_params(3))
    allocate(sptss_params(3))
    allocate(dfl_params(3))
    
    return
end
    
subroutine params_alloc
    ! primary parameter memory allocation subroutine used for 95% of allocated global arrays defined in PARAMS
    use params
    implicit none
    
    ! allocate memory for variables read in or calculated from xyzc DEM file in subroutine: PREPROCESSING
    allocate(dem_x(ndem))
    allocate(dem_y(ndem))
    allocate(dem_z(ndem))
    allocate(dem_meer(ndem))
    allocate(dem_pldr(ndem))
    allocate(dem_comp(ndem))
    allocate(dem_grid(ndem))
    allocate(dem_lndtyp(ndem))
    allocate(dem_bi_zone(ndem))
    allocate(dem_bi_map(ndem))
    allocate(dem_dpsb(ndem))
    allocate(er_codes(neco))
    allocate(er_shsb(neco,3))
    allocate(er_omar(neco,6))
    allocate(comp_eco(ncomp))         
    allocate(comp_act_dlt(ncomp)) 
    allocate(comp_ndem_all(ncomp))
    allocate(grid_ndem_all(ngrid))
    
    ! allocate memory for variables read in or calculated from compartment_out Hydro summary file in subroutine: PREPROCESSING
    allocate(stg_mx_yr(ncomp))
    allocate(stg_av_yr(ncomp))
    allocate(stg_av_smr(ncomp))
    allocate(stg_sd_smr(ncomp))
    allocate(sal_av_yr(ncomp))
    allocate(sal_av_smr(ncomp))
    allocate(sal_mx_14d_yr(ncomp))
    allocate(tmp_av_yr(ncomp))
    allocate(tmp_av_smr(ncomp))
    allocate(sed_dp_ow_yr(ncomp))
    allocate(sed_dp_mi_yr(ncomp))
    allocate(sed_dp_me_yr(ncomp))
    allocate(tidal_prism_ave(ncomp))
    allocate(ave_sepmar_stage(ncomp))
    allocate(ave_octapr_stage(ncomp))
    allocate(marsh_edge_erosion_rate(ncomp))
    allocate(ave_annual_tss(ncomp))
    allocate(stdev_annual_tss(ncomp))
    allocate(totalland_m2(ncomp))

    ! allocate memory for variables read in from previous year's compartment_out Hydro summary file in subroutine: PREPROCESSING
    allocate(stg_av_prev_yr(ncomp))
    allocate(sal_av_prev_yr(ncomp))
    
    ! define variables read in or calculated from vegtype ICM-LAVegMod summary file in subroutine: PREPROCESSING
    allocate(grid_comp(ngrid))
    allocate(grid_pct_water(ngrid))
    allocate(grid_pct_upland(ngrid))
    allocate(grid_pct_bare_old(ngrid))
    allocate(grid_pct_bare_new(ngrid)) 
    allocate(grid_pct_dead_flt(ngrid))
    allocate(grid_pct_vglnd_BLHF(ngrid))
    allocate(grid_pct_vglnd_SWF(ngrid))
    allocate(grid_pct_vglnd_FM(ngrid))
    allocate(grid_pct_vglnd_IM(ngrid))
    allocate(grid_pct_vglnd_BM(ngrid))
    allocate(grid_pct_vglnd_SM(ngrid))
    allocate(grid_FIBS_score(ngrid))
    
    ! allocate memory for global variables representing monthly summary files  in subroutine: PREPROCESSING
    allocate(stg_av_mons(ncomp,12))
    allocate(stg_mx_mons(ncomp,12))
    allocate(sed_dp_ow_mons(ncomp,12))
    allocate(sed_dp_mi_mons(ncomp,12))
    allocate(sed_dp_me_mons(ncomp,12))
    allocate(sal_av_mons(ncomp,12))
    allocate(tss_av_mons(ncomp,12))
    
   ! allocate memory for global variables sub-domain DEM file generated by ICM-BI-DEM in subroutine: PREPROCESSING
    allocate(dem_to_bidem(ndem))
    allocate(dem_z_bi(ndem_bi))

    ! allocate memory for variables for SAV statistical model read in during subroutine: PRE-PROCESSING 
    allocate(prior_int(neco))
    allocate(prior_slope(neco))
    
    ! allocate memory for global variables calculated in subroutine: EDGE_DELINEATION
    allocate(dem_edge(ndem))
    
    ! allocate memory for global variables calculated in subroutine: INUNDATION_DEPTHS
    allocate(dem_inun_dep(ndem,14))
    allocate(comp_ndem_wet(ncomp,14))
    allocate(grid_ndem_wet(ngrid,14))
    
    ! allocate memory for global variables calculated in subroutine: ORGANIC_ACCRETION & MINERAL_ACCRETION
    allocate(org_accr_cm(ndem))
    allocate(min_accr_cm(ndem))
    
    ! allocate memory for global variables used in subroutine:: MAP_BAREGROUND
    allocate(dem_bg_flag(ndem))
    
    ! allocate memory for variables calculated in subroutine: DISTANCE_TO_LAND
    allocate(dem_dtl(ndem))
    allocate(dem_dtl_ffibs(ndem))
    
    ! allocate memory for variables calculated in subroutine: SAV
    
    ! allocate memory for variable used to write to output files
    ! some output variables are allocated elsewhere, but these are only used for summarizing output
    allocate(dem_dz_cm(ndem))    
    allocate(lnd_change_flag(ndem))    
    allocate(grid_pct_upland_dry(ngrid))
    allocate(grid_pct_upland_wet(ngrid))
    allocate(grid_pct_bare(ngrid))
    allocate(grid_pct_flt(ngrid))
    allocate(grid_pct_edge(ngrid))
    allocate(grid_bed_z(ngrid))
    allocate(grid_land_z(ngrid))
    allocate(grid_gadwl_dep(ngrid,14))  
    allocate(grid_gwteal_dep(ngrid,9)) 
    allocate(grid_motduck_dep(ngrid,9))
    
    allocate(comp_pct_water(ncomp))
    allocate(comp_pct_wetland(ncomp))
    allocate(comp_pct_upland(ncomp))
    allocate(comp_wetland_z(ncomp))
    allocate(comp_water_z(ncomp))
    allocate(comp_edge_area(ncomp))

    allocate(er_sum(neco))
    allocate(er_counts(neco, 10))

    return
end
    
subroutine dem_params_alloc
    ! separate subroutine to allocate DEM grid due to the grid size not being known until DEM xyz file is preprocessed
    use params
    implicit none

    allocate(dem_index_mapped(n_dem_col,n_dem_row))
    
    return
end
